---
apiVersion: v1
kind: Service
metadata:
  name: mongo-0
  namespace: mongo
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: mongo-0
  ports:
  - name: mongo-0
    protocol: TCP
    nodePort: 30351
    port: 27017
    targetPort: mongo-port  

