---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-reports32-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

      
