apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        selector: mongo
    spec:
      containers:
      # - env:
      #   - name: MONGO_INITDB_ROOT_USERNAME
      #     valueFrom:
      #       secretKeyRef:
      #         key: username11
      #         name: lastpass
      #   - name: MONGO_INITDB_ROOT_PASSWORD
      #     valueFrom:
      #       secretKeyRef:
      #         key: password11
      #         name: lastpass
      - name: mongo
        image: mongo:6.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
          name: mongo-port
          protocol: TCP
        volumeMounts:
        - mountPath: /data/db
          name: mongo-store
  volumeClaimTemplates:
  - metadata:
      name: mongo-store
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: managed-premium-retain
# https://learn.microsoft.com/en-us/azure/aks/concepts-storage#storage-classes      

