---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-reports33-svc
spec:
  ports:
  - name: mosquitto-reports33-port
    nodePort: 30233    
    port: 1883
    targetPort: reports33-mqtt
    protocol: TCP
