---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: %APP%-%NODE%
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: eclipse-mosquitto:2.0.15
        name: %APP%-%NODE%

