---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: %APP%-%NODE%-pvc
spec:
  storageClassName: mongodb-storageclass
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi      

      
