---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-moto-pvc
spec:
  storageClassName: mongodb-storageclass
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi      

      
