apiVersion: v1
kind: Service
metadata:
  name: mongobi-0
  namespace: mongo
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: mongobi-0
  ports:
  - name: mongobi-0
    port: 30341
    protocol: TCP
    targetPort: 3307 

