apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-moto
  name: mongodb-moto-svc
spec:
  ports:
  - name: mongodb-moto-port
    nodePort: 30351
    port: 27017
    protocol: TCP
    targetPort: moto-mongo
  selector:
    app: mongodb-moto
  type: NodePort