apiVersion: v1
kind: Service
metadata:
  name: reports-mongodb-0
  namespace: mongo
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: reports-mongodb-0
  ports:
  - name: reports-mongodb-0
    port: 30361
    protocol: TCP
    targetPort: 27017 

