---
apiVersion: v1
kind: Service
metadata:
  name: %NODE%-api
  #namespace: default
  labels:
    app: %NODE%-api
spec:
  selector:
    app: %NODE%-api
  ports:
  - name: http
    protocol: TCP
    # port=available to other containers
    port: %API_PORT%
    # targetPort=exposed from inside container
    targetPort: %API_PORT%

