---
apiVersion: v1
kind: Service
metadata:
  name: reports31-api
  #namespace: default
  labels:
    app: reports31-api
spec:
  selector:
    app: reports31-api
  ports:
  - name: http
    protocol: TCP
    # port=available to other containers
    port: 5000
    # targetPort=exposed from inside container
    targetPort: 5000

