---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-reports31-svc
spec:
  ports:
  - name: mosquitto-reports31-port
    nodePort: 30231    
    port: 1883
    targetPort: reports31-mqtt
    protocol: TCP
