apiVersion: apps/v1
kind: Deployment
metadata:
  name: etl-reports11
spec:
  template:
    spec:
      containers:
      - name: etl-reports11
        env:
        # which database to use
        - name: MYSQL_HOST
          value: "reports11"
        - name: MYSQL_PORT
          value: "30011"
        - name: AZURE_DW
          value: "0"
        command: ["/bin/sh"]
        args:
          - -c
          - >-
              cron -f 
        # command: ["/bin/sleep", "3650d"]
        imagePullPolicy: Always
        volumeMounts:
        - name: foo
          mountPath: "/etc/foo"
          readOnly: true
      affinity:               
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - reports11
