apiVersion: apps/v1
kind: Deployment
metadata:
  name: etl-reports11
  labels:
    app: etl-reports11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etl-reports11
  template:
    metadata:
      labels:
        app: etl-reports11
    spec:
      hostNetwork: true
      dnsPolicy: Default
      containers:
      - name: etl-reports11
        image: brentgroves/etl-reports11:1
        env:
        # which database to use
        - name: MYSQL_HOST
          value: "reports11"
        - name: MYSQL_PORT
          value: "30011"
        - name: AZURE_DW
          value: "0"
        command: ["/bin/sh"]
        args:
          - -c
          - >-
              cron -f 
        # command: ["/bin/sleep", "3650d"]
        imagePullPolicy: Always
        volumeMounts:
        - name: foo
          mountPath: "/etc/foo"
          readOnly: true
      affinity:               
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - reports11
      volumes:
      - name: foo
        secret:
          secretName: db-user-pass
          optional: false # default setting; "mysecret" must exist    
        # imagePullPolicy: IfNotPresent
      restartPolicy: Always  
