---
apiVersion: v1
kind: Service
metadata:
  name: %SERVICE_NAME%
spec:
  ports:
  - name: %SERVICE_NAME%-port
    port: 3306
    targetPort: %SERVICE_NAME%
    nodePort: %NODE_PORT%    
    protocol: TCP
