apiVersion: apps/v1
kind: Deployment
metadata:
  name: %APP%-%NODE%
  labels:
    app: %APP%-%NODE%
spec:
  replicas: 1
  selector:
    matchLabels:
      app: %APP%-%NODE%
  strategy: {}
  template:
    metadata:
      labels:
        app: %APP%-%NODE%
    spec:
      containers:
      - name: %APP%-%NODE%
        image: mongo:%VER%
        imagePullPolicy: Always
        ports:
        - containerPort: %TARGET_PORT%
          name: %NODE%-%TARGET_PORT_NAME%
          protocol: TCP
        args:
        - -c
        - mongod --bind_ip_all --dbpath /data/db
        command:
        - /bin/sh
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: password
        volumeMounts:
        - name: %APP%-%NODE%-data-dir
          mountPath: "/data/db"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - %NODE%
      volumes:
      - name: %APP%-%NODE%-data-dir
        persistentVolumeClaim:
          claimName: %APP%-%NODE%-pvc