apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-moto
  labels:
    app: mongodb-moto
spec:
  serviceName: mongodb-moto-svc
  selector:
    matchLabels:
      app: mongodb-moto
  template:
    metadata:
      labels:
        app: mongodb-moto
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - moto
      containers:
      # https://phoenixnap.com/kb/kubernetes-mongodb#step-5-create-a-configmap
      - name: mongodb-moto
        image: mongo:6.0.3
        # args:
        # - -c
        # - mongod --bind_ip_all --dbpath /data/db
        # command:
        # - /bin/sh
        ports:
        - containerPort: 27017
          name: moto-mongo
          protocol: TCP
        volumeMounts:
        - name: mongodb-moto-data-dir
          mountPath: "/data/db"
        # - name: mongodb-users
        #   mountPath: /etc/mongodb-users
        #   readOnly: true
        - name: mongodb-scripts
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
        - name: mongodb-configmap
          mountPath: /config
          readOnly: true
      volumes:
      # - name: mongodb-users
      #   secret:
      #     secretName: mongodb-secret
      #     items:
      #     - key: mongo-root-username
      #       path: mongo-root-username
      #       mode: 0444
      #     - key: mongo-root-password
      #       path: mongo-root-password
      #       mode: 0444
      - name: mongodb-scripts
        configMap:
          name: mongodb-configmap
          items:
          - key: ensure-users.js
            path: ensure-users.js
      - name: mongodb-configmap
        configMap:
          name: mongodb-configmap
          items:
          - key: mongo.conf
            path: mongo.conf
      - name: mongodb-moto-data-dir
        persistentVolumeClaim:
          claimName: mongodb-moto-pvc