apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-reports31
spec:
  template:
    spec:
      containers:
      - name: mongodb-reports31
        imagePullPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - reports31
