---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-reports31-svc
spec:
  ports:
  - name: mongodb-reports31-port
    nodePort: 30331    
    port: 27017
    targetPort: reports31-mongo
    protocol: TCP
