---
apiVersion: v1
kind: Service
metadata:
  name: bi-connector-svc
  labels:
    app: bi-connector
spec:
  ports:
  - port: 3307
    targetPort: bi-port
    name: biport
  clusterIP: None
  selector:
    app: bi-connector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bi-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bi-connector
  template:
    metadata:
      labels:
        app: bi-connector
    spec:
      containers:
      - name: bi-connector
        image: brentgroves/bi-connector:1
        ports:
        - containerPort: 3307
          name: bi-port