---
apiVersion: v1
kind: Service
metadata:
  name: bi-connector-svc
  labels:
    app: bi-connector
spec:
  ports:
  - port: 3307
    targetPort: 3307
  clusterIP: None
  selector:
    app: bi-connector
# reports-mongodb-svc   ClusterIP      None         27017/TCP         7d4h
