apiVersion: v1
kind: Service
metadata:
  name: bi-connector-lb
spec:
  type: LoadBalancer
  ports:
  - port: 30341
    name: bi-lb-port
    protocol: TCP
    targetPort: bi-port
  selector:
      app: bi-connector

