---
apiVersion: v1
kind: Service
metadata:
  name: bi-connector-np
  namespace: mongo
spec:
  type: NodePort
  selector:
      app: bi-connector
  ports:
  - name: bi-np-port
    protocol: TCP
    nodePort: 30351
    port: 3307
    targetPort: bi-port  

