apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-log-reports01
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  local:
    path: /mnt/mongo/logs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - reports01
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongo-logs-storage
  volumeMode: Filesystem
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pvc-mdb2-reports01
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi
#   storageClassName: local-storage
#   volumeMode: Filesystem