# https://stackoverflow.com/questions/68366456/mongodb-community-kubernetes-operator-and-custom-persistent-volumes

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongo-data-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer