echo "mg.odbcalbion" > /etc/lastpass/username
echo "Mob3xalbion" > /etc/lastpass/password
echo "mgadmin" > /etc/lastpass/username2
echo "WeDontSharePasswords1\!" > /etc/lastpass/password2
echo "root" > /etc/lastpass/username3
echo "password" > /etc/lastpass/password3
echo "MGEdonReportsws@plex.com" > /etc/lastpass/username4
echo "9f45e3d-67ed-" > /etc/lastpass/password4
echo "reports31" > /etc/lastpass/MYSQL_HOST
echo "30031" > /etc/lastpass/MYSQL_PORT
echo "0" > /etc/lastpass/AZURE_DW
echo "reports31" > /etc/lastpass/MONGO_HOST
echo "30331" > /etc/lastpass/MONGO_PORT
echo "reports" > /etc/lastpass/MONGO_DB
